"""entries table

Revision ID: 366db25164c2
Revises: 
Create Date: 2020-04-01 19:32:39.435448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366db25164c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=20), nullable=False),
    sa.Column('street', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('province', sa.String(length=2), nullable=False),
    sa.Column('zipcode', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_description'), 'entry', ['description'], unique=False)
    op.create_index(op.f('ix_entry_title'), 'entry', ['title'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('quanity_left', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productid'], ['product.id'], ),
    sa.PrimaryKeyConstraint('productid')
    )
    op.create_table('procurement',
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('quantity_purchased', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['productid'], ['product.id'], ),
    sa.PrimaryKeyConstraint('productid', 'date')
    )
    op.create_table('transaction',
    sa.Column('customerid', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('total_sales', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customerid'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['productid'], ['product.id'], ),
    sa.PrimaryKeyConstraint('customerid', 'productid', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('procurement')
    op.drop_table('inventory')
    op.drop_table('product')
    op.drop_index(op.f('ix_entry_title'), table_name='entry')
    op.drop_index(op.f('ix_entry_description'), table_name='entry')
    op.drop_table('entry')
    op.drop_table('customer')
    # ### end Alembic commands ###
